apiVersion: v1
kind: Pod
metadata:
   name: php-pod
   labels:
     env: testing
spec:
   volumes:
     - name: pvc-storage
       persistentVolumeClaim:
        claimName: pvc1
   containers:
     - name: php-con
       image: vimal13/apache-webserver-php
       volumeMounts:
        -  mountPath: /var/www/html
           name: pvc-storage

